// <auto-generated />
using System;
using BackendApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Models.AllEstatus", b =>
                {
                    b.Property<int>("IdEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idestatus");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstatus"));

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estatus");

                    b.HasKey("IdEstatus");

                    b.ToTable("estatus");

                    b.HasData(
                        new
                        {
                            IdEstatus = 1,
                            Estatus = "Activo"
                        },
                        new
                        {
                            IdEstatus = 2,
                            Estatus = "Inactivo"
                        },
                        new
                        {
                            IdEstatus = 3,
                            Estatus = "Pendiente"
                        },
                        new
                        {
                            IdEstatus = 4,
                            Estatus = "Pagado"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.AllEstatusPay", b =>
                {
                    b.Property<int>("IdEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idestatus");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstatus"));

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estatus");

                    b.HasKey("IdEstatus");

                    b.ToTable("estatus_payment");

                    b.HasData(
                        new
                        {
                            IdEstatus = 1,
                            Estatus = "Registrado"
                        },
                        new
                        {
                            IdEstatus = 2,
                            Estatus = "Pagado"
                        },
                        new
                        {
                            IdEstatus = 3,
                            Estatus = "Anulado"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.ApiResponse", b =>
                {
                    b.Property<int>("IdResponse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idresponse");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdResponse"));

                    b.Property<int?>("IdPrepoliza")
                        .HasColumnType("integer")
                        .HasColumnName("idprepoliza");

                    b.Property<string>("Jsonn")
                        .HasColumnType("text")
                        .HasColumnName("jsonn");

                    b.Property<string>("Respuesta")
                        .HasColumnType("text")
                        .HasColumnName("respuesta");

                    b.HasKey("IdResponse");

                    b.ToTable("responseapis");
                });

            modelBuilder.Entity("BackendApi.Models.Bank", b =>
                {
                    b.Property<int>("IdBco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idbco");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBco"));

                    b.Property<string>("CBanco")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("cbanco");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("integer")
                        .HasColumnName("idestatus");

                    b.Property<string>("XBanco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("xbanco");

                    b.HasKey("IdBco");

                    b.ToTable("banks");
                });

            modelBuilder.Entity("BackendApi.Models.City", b =>
                {
                    b.Property<int>("IdCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idciudad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCiudad"));

                    b.Property<int>("CCiudad")
                        .HasColumnType("integer")
                        .HasColumnName("cciudad");

                    b.Property<int>("CEstado")
                        .HasColumnType("integer")
                        .HasColumnName("cestado");

                    b.Property<int>("CPais")
                        .HasColumnType("integer")
                        .HasColumnName("cpais");

                    b.Property<string>("CiuDescripcionC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciu_descripcion_c");

                    b.Property<string>("CiuDescripcionL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciu_descripcion_l");

                    b.HasKey("IdCiudad");

                    b.ToTable("maciudades");
                });

            modelBuilder.Entity("BackendApi.Models.Comission", b =>
                {
                    b.Property<int>("IdComission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcomission");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdComission"));

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("comission");

                    b.Property<DateTime?>("DatePay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_pay");

                    b.Property<DateTime>("DateRegister")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_register");

                    b.Property<DateTime?>("DateSend")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_send");

                    b.Property<int>("Enviado")
                        .HasColumnType("integer")
                        .HasColumnName("enviado");

                    b.Property<int?>("IdCoverage")
                        .HasColumnType("integer")
                        .HasColumnName("idcoverage");

                    b.Property<int>("IdPoliza")
                        .HasColumnType("integer")
                        .HasColumnName("idpoliza");

                    b.Property<int>("Pagado")
                        .HasColumnType("integer")
                        .HasColumnName("pagado");

                    b.Property<string>("RefPay")
                        .HasColumnType("text")
                        .HasColumnName("ref_pay");

                    b.HasKey("IdComission");

                    b.ToTable("comissions");
                });

            modelBuilder.Entity("BackendApi.Models.Company", b =>
                {
                    b.Property<int>("IdCmpy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcmpy");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCmpy"));

                    b.Property<int>("CEstado")
                        .HasColumnType("integer")
                        .HasColumnName("cestado");

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("ci");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("integer")
                        .HasColumnName("idestatus");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("typ");

                    b.Property<string>("XCity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("xcity");

                    b.Property<string>("XDir")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("xdir");

                    b.HasKey("IdCmpy");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("BackendApi.Models.EmailValidation", b =>
                {
                    b.Property<int>("IdValidacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idvalidacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdValidacion"));

                    b.Property<int>("Codigo")
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("integer")
                        .HasColumnName("idestatus");

                    b.HasKey("IdValidacion");

                    b.ToTable("validaciones_email");
                });

            modelBuilder.Entity("BackendApi.Models.FrequencyTypes", b =>
                {
                    b.Property<int>("IdFrecu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idfrecu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFrecu"));

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frecuencia");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("letra");

                    b.HasKey("IdFrecu");

                    b.ToTable("frequency");

                    b.HasData(
                        new
                        {
                            IdFrecu = 1,
                            Frecuencia = "Anual",
                            Letra = "A"
                        },
                        new
                        {
                            IdFrecu = 2,
                            Frecuencia = "Semestral",
                            Letra = "S"
                        },
                        new
                        {
                            IdFrecu = 3,
                            Frecuencia = "Cuatrimestral",
                            Letra = "C"
                        },
                        new
                        {
                            IdFrecu = 4,
                            Frecuencia = "Trimestral",
                            Letra = "T"
                        },
                        new
                        {
                            IdFrecu = 5,
                            Frecuencia = "Mensual",
                            Letra = "M"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.MaritalStatus", b =>
                {
                    b.Property<int>("IdEcivil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idecivil");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEcivil"));

                    b.Property<string>("Ecivil")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ecivil");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("letra");

                    b.HasKey("IdEcivil");

                    b.ToTable("ecivil");

                    b.HasData(
                        new
                        {
                            IdEcivil = 1,
                            Ecivil = "Soltero",
                            Letra = "S"
                        },
                        new
                        {
                            IdEcivil = 2,
                            Ecivil = "Casado",
                            Letra = "C"
                        },
                        new
                        {
                            IdEcivil = 3,
                            Ecivil = "Viudo",
                            Letra = "V"
                        },
                        new
                        {
                            IdEcivil = 4,
                            Ecivil = "Divorciado",
                            Letra = "D"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.Payment", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idpago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime>("FecDd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fec_dd");

                    b.Property<DateTime>("FecHt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fec_ht");

                    b.Property<DateTime>("FecPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fec_pago");

                    b.Property<int>("FrmPago")
                        .HasColumnType("integer")
                        .HasColumnName("frm_pago");

                    b.Property<int>("IdHijo")
                        .HasColumnType("integer")
                        .HasColumnName("idhijo");

                    b.Property<int>("MntPagado")
                        .HasColumnType("integer")
                        .HasColumnName("mnt_pagado");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.HasKey("IdPago");

                    b.ToTable("pagos");
                });

            modelBuilder.Entity("BackendApi.Models.Policy", b =>
                {
                    b.Property<int>("IdPoliza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idpoliza");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPoliza"));

                    b.Property<int>("CRamoSisip")
                        .HasColumnType("integer")
                        .HasColumnName("cramo_sisip");

                    b.Property<DateTime>("DateAdmission")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_admission");

                    b.Property<DateTime>("DateDdPolicy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_dd_policy");

                    b.Property<DateTime>("DateDdReceipt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_dd_receipt");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_emission");

                    b.Property<DateTime>("DateHtPolicy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_ht_policy");

                    b.Property<DateTime>("DateHtReceipt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_ht_receipt");

                    b.Property<DateTime>("DatePay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_pay");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("frequency");

                    b.Property<int>("IdCmpy")
                        .HasColumnType("integer")
                        .HasColumnName("idcmpy");

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer")
                        .HasColumnName("idproduct");

                    b.Property<int>("MonthPolicy")
                        .HasColumnType("integer")
                        .HasColumnName("monthpolicy");

                    b.Property<string>("NroPolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nro_policy");

                    b.Property<string>("NroReceipt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nro_receipt");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<decimal>("Prima")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("prima");

                    b.Property<decimal?>("TasaBcv")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("tasabcv");

                    b.Property<int>("YearPolicy")
                        .HasColumnType("integer")
                        .HasColumnName("yearpolicy");

                    b.HasKey("IdPoliza");

                    b.ToTable("polizas");
                });

            modelBuilder.Entity("BackendApi.Models.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idproduct");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduct"));

                    b.Property<string>("CPlanSisip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cplan_sisip");

                    b.Property<int?>("CRamoSisip")
                        .HasColumnType("integer")
                        .HasColumnName("cramo_sisip");

                    b.Property<int>("IdCmpy")
                        .HasColumnType("integer")
                        .HasColumnName("idcmpy");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("integer")
                        .HasColumnName("idestatus");

                    b.Property<int>("IdProductoSisip")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto_sisip");

                    b.Property<int>("IdRamo")
                        .HasColumnType("integer")
                        .HasColumnName("idramo");

                    b.HasKey("IdProduct");

                    b.ToTable("products");
                });

            modelBuilder.Entity("BackendApi.Models.ProductCoverage", b =>
                {
                    b.Property<int>("IdCoverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcoverage");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCoverage"));

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer")
                        .HasColumnName("idproduct");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Percent")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("percent");

                    b.HasKey("IdCoverage");

                    b.ToTable("products_coverage");
                });

            modelBuilder.Entity("BackendApi.Models.ProductUser", b =>
                {
                    b.Property<int>("IdOption")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idoption");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOption"));

                    b.Property<decimal>("Comission")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("comission");

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer")
                        .HasColumnName("idproduct");

                    b.Property<int>("IdSeller")
                        .HasColumnType("integer")
                        .HasColumnName("idseller");

                    b.Property<int>("Permiso")
                        .HasColumnType("integer")
                        .HasColumnName("permiso");

                    b.HasKey("IdOption");

                    b.ToTable("products_user");
                });

            modelBuilder.Entity("BackendApi.Models.ProfileUser", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idperfil");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPerfil"));

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("perfil");

                    b.HasKey("IdPerfil");

                    b.ToTable("profiles");

                    b.HasData(
                        new
                        {
                            IdPerfil = 1,
                            Perfil = "Admin"
                        },
                        new
                        {
                            IdPerfil = 2,
                            Perfil = "Seller Master"
                        },
                        new
                        {
                            IdPerfil = 3,
                            Perfil = "Seller"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.Ramo", b =>
                {
                    b.Property<int>("IdRamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idramo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRamo"));

                    b.Property<int?>("CRamoSisip")
                        .HasColumnType("integer")
                        .HasColumnName("cramo_sisip");

                    b.Property<byte[]>("Condicionado")
                        .HasColumnType("bytea")
                        .HasColumnName("condicionado");

                    b.Property<string>("XRamoSisip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("xramo_sisip");

                    b.HasKey("IdRamo");

                    b.ToTable("ramos");

                    b.HasData(
                        new
                        {
                            IdRamo = 1,
                            CRamoSisip = 5,
                            XRamoSisip = "ACCIDENTES PERSONALES"
                        },
                        new
                        {
                            IdRamo = 2,
                            CRamoSisip = 9,
                            XRamoSisip = "GASTOS FUNERARIOS"
                        },
                        new
                        {
                            IdRamo = 3,
                            CRamoSisip = 0,
                            XRamoSisip = "RCV"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.Relationship", b =>
                {
                    b.Property<int>("IdParen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idparen");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdParen"));

                    b.Property<int>("IdEstatus")
                        .HasColumnType("integer")
                        .HasColumnName("idestatus");

                    b.Property<string>("ParentescoName")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("parentesco");

                    b.HasKey("IdParen");

                    b.ToTable("parentesco");

                    b.HasData(
                        new
                        {
                            IdParen = 1,
                            IdEstatus = 1,
                            ParentescoName = "Titular"
                        },
                        new
                        {
                            IdParen = 2,
                            IdEstatus = 1,
                            ParentescoName = "Conyuge"
                        },
                        new
                        {
                            IdParen = 3,
                            IdEstatus = 1,
                            ParentescoName = "Hijo (a)"
                        },
                        new
                        {
                            IdParen = 4,
                            IdEstatus = 2,
                            ParentescoName = "Abuelos (as)"
                        },
                        new
                        {
                            IdParen = 5,
                            IdEstatus = 2,
                            ParentescoName = "Tios (as)"
                        },
                        new
                        {
                            IdParen = 6,
                            IdEstatus = 1,
                            ParentescoName = "Padres"
                        },
                        new
                        {
                            IdParen = 7,
                            IdEstatus = 2,
                            ParentescoName = "Hermano (a)"
                        },
                        new
                        {
                            IdParen = 8,
                            IdEstatus = 1,
                            ParentescoName = "Otro"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.Seller", b =>
                {
                    b.Property<int>("IdSeller")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idseller");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSeller"));

                    b.Property<string>("Banco")
                        .HasColumnType("text")
                        .HasColumnName("banco");

                    b.Property<int?>("CEstato")
                        .HasColumnType("integer")
                        .HasColumnName("cestado");

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("ci");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<decimal?>("Comission")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("comission");

                    b.Property<string>("ECivil")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("ecivil");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FPay")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("fpay");

                    b.Property<DateTime?>("FechaNac")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nac");

                    b.Property<int?>("IdEstatus")
                        .HasColumnType("integer")
                        .HasColumnName("idestatus");

                    b.Property<int>("IdPapa")
                        .HasColumnType("integer")
                        .HasColumnName("idpapa");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("NroCta")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nrocta");

                    b.Property<byte[]>("PdfCed")
                        .HasColumnType("bytea")
                        .HasColumnName("pdf_ced");

                    b.Property<byte[]>("PdfRif")
                        .HasColumnType("bytea")
                        .HasColumnName("pdf_rif");

                    b.Property<string>("Sexx")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("sexx");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("typ");

                    b.Property<string>("XCity")
                        .HasColumnType("text")
                        .HasColumnName("xcity");

                    b.Property<string>("XDir")
                        .HasColumnType("text")
                        .HasColumnName("xdir");

                    b.HasKey("IdSeller");

                    b.ToTable("sellers");
                });

            modelBuilder.Entity("BackendApi.Models.SellerCoverageComission", b =>
                {
                    b.Property<int>("IdSeller")
                        .HasColumnType("integer")
                        .HasColumnName("idseller");

                    b.Property<int>("IdCoverage")
                        .HasColumnType("integer")
                        .HasColumnName("idcoverage");

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<decimal?>("Comission")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("comission");

                    b.HasKey("IdSeller", "IdCoverage");

                    b.ToTable("seller_coverage_comission");
                });

            modelBuilder.Entity("BackendApi.Models.State", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idestado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstado"));

                    b.Property<int>("CEstado")
                        .HasColumnType("integer")
                        .HasColumnName("cestado");

                    b.Property<int>("CPais")
                        .HasColumnType("integer")
                        .HasColumnName("cpais");

                    b.Property<string>("XDescripcionC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("xdescripcion_c");

                    b.Property<string>("XDescripcionL")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("xdescripcion_l");

                    b.HasKey("IdEstado");

                    b.ToTable("maestados");

                    b.HasData(
                        new
                        {
                            IdEstado = 1,
                            CEstado = 1,
                            CPais = 58,
                            XDescripcionC = "Dtto Capital",
                            XDescripcionL = "Distrito Capital"
                        },
                        new
                        {
                            IdEstado = 2,
                            CEstado = 2,
                            CPais = 58,
                            XDescripcionC = "Amazonas",
                            XDescripcionL = "Amazonas"
                        },
                        new
                        {
                            IdEstado = 3,
                            CEstado = 3,
                            CPais = 58,
                            XDescripcionC = "Anzoategui",
                            XDescripcionL = "Anzoategui"
                        },
                        new
                        {
                            IdEstado = 4,
                            CEstado = 4,
                            CPais = 58,
                            XDescripcionC = "Apure",
                            XDescripcionL = "Apure"
                        },
                        new
                        {
                            IdEstado = 5,
                            CEstado = 5,
                            CPais = 58,
                            XDescripcionC = "Aragua",
                            XDescripcionL = "Aragua"
                        },
                        new
                        {
                            IdEstado = 6,
                            CEstado = 6,
                            CPais = 58,
                            XDescripcionC = "Barinas",
                            XDescripcionL = "Barinas"
                        },
                        new
                        {
                            IdEstado = 7,
                            CEstado = 7,
                            CPais = 58,
                            XDescripcionC = "Bolivar",
                            XDescripcionL = "Bolivar"
                        },
                        new
                        {
                            IdEstado = 8,
                            CEstado = 8,
                            CPais = 58,
                            XDescripcionC = "Carabobo",
                            XDescripcionL = "Carabobo"
                        },
                        new
                        {
                            IdEstado = 9,
                            CEstado = 9,
                            CPais = 58,
                            XDescripcionC = "Cojedes",
                            XDescripcionL = "Cojedes"
                        },
                        new
                        {
                            IdEstado = 10,
                            CEstado = 10,
                            CPais = 58,
                            XDescripcionC = "Delta Amacuro",
                            XDescripcionL = "Delta Amacuro"
                        },
                        new
                        {
                            IdEstado = 11,
                            CEstado = 11,
                            CPais = 58,
                            XDescripcionC = "Falcon",
                            XDescripcionL = "Falcon"
                        },
                        new
                        {
                            IdEstado = 12,
                            CEstado = 12,
                            CPais = 58,
                            XDescripcionC = "Guarico",
                            XDescripcionL = "Guarico"
                        },
                        new
                        {
                            IdEstado = 13,
                            CEstado = 13,
                            CPais = 58,
                            XDescripcionC = "Lara",
                            XDescripcionL = "Lara"
                        },
                        new
                        {
                            IdEstado = 14,
                            CEstado = 14,
                            CPais = 58,
                            XDescripcionC = "Merida",
                            XDescripcionL = "Merida"
                        },
                        new
                        {
                            IdEstado = 15,
                            CEstado = 15,
                            CPais = 58,
                            XDescripcionC = "Monagas",
                            XDescripcionL = "Monagas"
                        },
                        new
                        {
                            IdEstado = 16,
                            CEstado = 16,
                            CPais = 58,
                            XDescripcionC = "Nueva Esparta",
                            XDescripcionL = "Nueva Esparta"
                        },
                        new
                        {
                            IdEstado = 17,
                            CEstado = 17,
                            CPais = 58,
                            XDescripcionC = "Portuguesa",
                            XDescripcionL = "Portuguesa"
                        },
                        new
                        {
                            IdEstado = 18,
                            CEstado = 18,
                            CPais = 58,
                            XDescripcionC = "Sucre",
                            XDescripcionL = "Sucre"
                        },
                        new
                        {
                            IdEstado = 19,
                            CEstado = 19,
                            CPais = 58,
                            XDescripcionC = "Tachira",
                            XDescripcionL = "Tachira"
                        },
                        new
                        {
                            IdEstado = 20,
                            CEstado = 20,
                            CPais = 58,
                            XDescripcionC = "Trujillo",
                            XDescripcionL = "Trujillo"
                        },
                        new
                        {
                            IdEstado = 21,
                            CEstado = 21,
                            CPais = 58,
                            XDescripcionC = "Yaracuy",
                            XDescripcionL = "Yaracuy"
                        },
                        new
                        {
                            IdEstado = 22,
                            CEstado = 22,
                            CPais = 58,
                            XDescripcionC = "Zulia",
                            XDescripcionL = "Zulia"
                        },
                        new
                        {
                            IdEstado = 23,
                            CEstado = 23,
                            CPais = 58,
                            XDescripcionC = "La Guaira",
                            XDescripcionL = "La Guaira"
                        },
                        new
                        {
                            IdEstado = 24,
                            CEstado = 24,
                            CPais = 58,
                            XDescripcionC = "Miranda",
                            XDescripcionL = "Miranda"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iduser");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<int?>("Cedula")
                        .HasColumnType("integer")
                        .HasColumnName("cedula");

                    b.Property<string>("Clave")
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<int?>("IdEstatus")
                        .HasColumnType("integer")
                        .HasColumnName("idestatus");

                    b.Property<int?>("IdPerfil")
                        .HasColumnType("integer")
                        .HasColumnName("idperfil");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("UserLogin")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.Property<string>("UserName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("user_name");

                    b.HasKey("IdUser");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
